name: "Continuous Delivery"
on:
  push:
    branches:
      - main
      - dev

env:
  NAME: cemu

jobs:
  build:
    name: "Building cemu"
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]
        python: [3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: rlespinasse/github-slug-action@v3.x

    - name: "Install Pre-requisite for Linux build"
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y build-essential python3-dev python3-pip python3-wheel python3-setuptools

    - name: "Install Pre-requisite for Windows build"
      if: startsWith(matrix.os, 'windows')
      shell: pwsh
      run: |
        echo todo


    - name: Build artifact
      shell: bash
      run: |
        mkdir build
        python --version
        python -m pip --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --user --upgrade -r requirements.txt
        python3 setup.py install --user

    - name: Publish artifact
      id: publish_artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}_${{ matrix.os }}_${{ env.GITHUB_REF_SLUG }}_${{ env.GITHUB_SHA_SHORT }}
        path: build/
