name: Package Application with Pyinstaller

on:
  push:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: main.spec

    - uses: actions/upload-artifact@v2
      with:
        name: cemu
        path: dist/windows
